# eksctl create cluster -f njd28b-cluster.yaml 
#
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: njd28b
  region: us-west-2

nodeGroups:
  - name: njd28-ng1
    instanceType: t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 40

  - name: njd28-ng2
    instanceType: t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 40

  - name: njd28-ng3
    instanceType: t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 40

  - name: njd28-ng4
    instanceType: t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 40
